### ISSUE TITLE
Google Maps Integration throws warning on console

### ISSUE THREAD

**Issue by BA-Webimax** [CherryFramework/cherry-plugin#14]
The enqueue call being used in cherry-plugin/includes/plugin-script.php on line 39 causes the Maps API to throw this error...

**"Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required"**

Changing the call to...

`wp_register_script( 'googlemapapis', '//maps.googleapis.com/maps/api/js?v=3.exp', array('jquery'), false, false );`

...will stop the warning. The use of the sensor parameter is deprecated and can be safely removed.

**Comment by cheh** [comment]
https://github.com/CherryFramework/cherry-plugin/commit/ca2b5cec32d91d9e05bfb55ec8a45ffc1780048b
