### ISSUE TITLE
Possible vulnerability

### ISSUE THREAD

**Issue by carogutt** [CherryFramework/cherry-plugin#16]
Hi, I found this post: https://www.pluginvulnerabilities.com/2016/06/22/old-vulnerability-report-arbitrary-file-viewing-vulnerability-in-cherry-plugin/

Should be good to check plugin or ask for a review of this post.

:)

**Comment by dkfiresky** [comment]
@carogutt, thanks for your interest.

Described vulnerability was fixed long time before the article was written.
As an article says, it's an old vulnerability in the plugin version 1.2.6.

Current version of the plugin is [__1.2.8.1__](https://github.com/CherryFramework/cherry-plugin/releases/tag/v1.2.8.1), which already contains the required fixes.

Reference: #6

**Comment by carogutt** [comment]
Thanks for the update :)
