### ISSUE TITLE
Authenticated Persistent Cross-Site Scripting (XSS) Vulnerability

### ISSUE THREAD

**Issue by PluginVulnerabilities** [CherryFramework/cherry-plugin#17]
The AJAX accessible function cherry_mtc_save(), in the file /includes/plugin-assets.php, is accessible to any logged in user despite it looking like it is only intended to be accessed by Administrator level users. That can be used for persistent cross-site scripting (XSS) by inputting JavaScript code in the data[mtc_mode_description] value saved through that. More detail on the issue can be found in our [post about it](https://www.pluginvulnerabilities.com/2016/06/30/authenticated-persistent-cross-site-scripting-xss-vulnerability-in-cherry-plugin/).

We contacted you privately about this a week ago, but haven't heard back from you.

**Comment by cheh** [comment]
@PluginVulnerabilities,

What your opinion about the fix - https://github.com/CherryFramework/cherry-plugin/pull/22?

**Comment by PluginVulnerabilities** [comment]
That looks to take care of the persistent XSS portion of the issue.

The function cherry_mtc_save() still could use a restriction on which logged-in users can make changes to the settings and protection against cross-site request forgery (CSRF).
