### ISSUE TITLE
tmbhtest.com 403

### ISSUE THREAD

**Issue by brianfeeley** [CherryFramework/cherry-plugin#19]
I am showing 403 errors on the backend of WordPress in the wp-admin/update-core.php

It seems the plugin is referencing an old domain that is no longer valid: tmbhtest.com which is defined here.https://github.com/CherryFramework/cherry-plugin/blob/master/cherry-plugin.php#L32

**Comment by brianfeeley** [comment]
Any chance we can get an update on this?

**Comment by szepeviktor** [comment]
Is it an update URL?

**Comment by brianfeeley** [comment]
I think so but I didn't find a different URL to replace it with: http://tmbhtest.com/cherryframework.com/components_update/

**Comment by szepeviktor** [comment]
@boryn See https://github.com/CherryFramework/cherry-plugin/commit/2e44e420456782b3a93dc24ff9de8792560201d1#diff-ee7e63bc08fc5e43aad6b25214404ac7
