### ISSUE TITLE
Stray %s in German language file

### ISSUE THREAD

**Issue by szepeviktor** [CherryFramework/cherry-plugin#23]
@cheh Could you please remove %s here?
https://github.com/CherryFramework/cherry-plugin/blob/master/languages/cherry-plugin-de_DE.po#L4135-L4136

**Comment by cheh** [comment]
@szepeviktor, as far as I know, this is an "obsolete messages" - http://pology.nedohodnik.net/doc/user/en_US/ch-poformat.html

**Comment by szepeviktor** [comment]
Excuse me.
It is really in theme.
It was fixed in https://github.com/CherryFramework/CherryFramework/commit/eb7c9e2bf276dc0b358929f6afae361dc85264f4#diff-d84d7b6a60e30f009795b374028226b6L3451

**Comment by cheh** [comment]
👍
