### ISSUE TITLE
Arbitrary file upload vulnerability

### ISSUE THREAD

**Issue by marcS0H** [CherryFramework/cherry-plugin#6]
Hi there,

It seems that anybody can upload files to "/admin/import-export/upload.php" (which would be accessible using an URL like "http://somesite.com/wp-content/plugins/cherry-plugin/admin/import-export/upload.php").

It is then very easy for someone to put malicious backdoors on a target website :-/

**Comment by gsouquet** [comment]
Any research around that? I help a friend that faces some issue on his website that uses CherryPlugin.
This could be the root of his issue.

Thanks!

**Comment by cheh** [comment]
Hi!

We already fixed this - https://github.com/CherryFramework/cherry-plugin/commit/95c6cfc54fbba1577ca623c2662f2127755b148a.
